# The following does not do anything.

on:
  push:
    branches:
      - master

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Hello, GitHub Actions!"